# Generated by Django 6.0.6 on 2026-07-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learner",
            name="firebase_uid",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True, unique=True
            ),
        ),
    ]
